### ISSUE TITLE
Cahoots 0.2.7 breaks https://security.google.com/settings/security/activity with Firefox 34

### ISSUE THREAD

**Issue by momu** [getcahoots/extension#11]
With enabled Cahoots Extension the Google Activity page is stuck (see attachment). Disabling it makes the page working again.

![screenshot](https://cloud.githubusercontent.com/assets/1451642/5215471/34e3ca5c-7628-11e4-91f0-b48da0f6b98d.png)

**Comment by webkodierer** [comment]
cannot reproduce. this might be solved with version 0.2.9.
