### ISSUE TITLE
stylesheets overwriting lglobal link style in webkit

### ISSUE THREAD

**Issue by xi** [getcahoots/extension#33]
In extension/src/main/resources/css/cahoots-tooltipster.css there is the following rule:

```
a:-webkit-any-link {
    text-decoration: none;
}
```

This is very specific and overwrites other styles. If links are only distinguishable from normal text by text-decoration (e.g. underline which is the default in most browsers) this really affects usability.

This not in the [upstream code](https://github.com/iamceege/tooltipster/blob/master/css/tooltipster.css). I do not know how this got here. Maybe you simply need to update tooltipster, maybe this stylesheet is custom and you need to fix it locally.

**Comment by freimuth82** [comment]
I don't know why I came across this issue this late, but today I ran into it too. Please remove this global rule, it affects too many webpages because of the strength of this selector. I need to deactivate your extension by now until this is fixed.

**Comment by artingei** [comment]
I'm starting now to refactor css completely to avoid this and fix some more stuff I am not happy with.

**Comment by artingei** [comment]
https://github.com/getcahoots/extension/tree/enhancement/33_cssrefactoring

**Comment by artingei** [comment]
we made some rearrangements:

- we will fix bug now
- refactoring will be tackled with cahoots 2.0

therefore i am going to rename this issue (again).
