### ISSUE TITLE
Firefox addon highlights any string "null" on web pages

### ISSUE THREAD

**Issue by flxtr** [getcahoots/extension#38]
The string "null" is highlighted by the Cahoots Firefox addon.

![Highlighted string "null" with mouse over](http://flxtr.de/null.png)

**OS:** Ubuntu 14.04
**Browser:** Firefox 39.0 (from the Ubuntu repos)
**Cahoots addon:** 1.1.4

**Comment by eskimoblood** [comment]
It happens in chrome as well.

**Comment by webkodierer** [comment]
thanks @flxtr and @eskimoblood for sharing this!
There was a problem with data that should be fixed now. Update of extension itself is not necessary. Can you confirm the problem to be solved?

**Comment by flxtr** [comment]
Thanks @webkodierer. The problem is solved for me. Sorry for the delay in response. I was not online over the holidays.
