### ISSUE TITLE
not working with Firefox 50.1.0

### ISSUE THREAD

**Issue by GiantCrocodile** [getcahoots/extension#44]
I don't see markup for any name or something - it simply not works for me over here. I'm using Firefox 50.1.0. Tried on several German newspaper sites.

**Comment by webkodierer** [comment]
ok, now following. we'll definitly investigate. is it still not working? e.g. this page here: 
http://www.sueddeutsche.de/politik/-wetterleuchten-1.3315110
it definitly "works for me" on FF 50.1.0 on mac.

**Comment by GiantCrocodile** [comment]
@webkodierer no it doesn't work for me on this specific page: not with Windows, not with Linux. There is nothing new next to the name 'Stefan Kornelius'. Maybe it is incompatible with latest version of Adblock Plus or NoScript.

**Comment by webkodierer** [comment]
alright. thanks for reporting and providing additional information. will catch up in a few days.

**Comment by webkodierer** [comment]
Old ticket. There have been many upgrades in the meantime. Please reopen if issues still exist.
