### ISSUE TITLE
Replace endpoint URL

### ISSUE THREAD

**Issue by akoenig** [getcahoots/extension#48]
Hi @webkodierer and @artingei,

I moved the backend to [now.sh](https://now.sh) which brings us some benefits, like

  * SSL certs for free
  * Easier deployment / no manual management of the infrastructure

Due to this fact, we have to make sure that the extension fetches the data from this URL: https://cahoots.now.sh/v2 (e.g. https://cahoots.now.sh/v2/persons)

**Comment by webkodierer** [comment]
resolved
