### ISSUE TITLE
Pale Moon Support

### ISSUE THREAD

**Issue by beerisgood** [getcahoots/extension#6]
I can't install the addon with Pale Moon so please add support for the Pale Moon browser: http://www.palemoon.org

Pale Moon have a own GUID: {8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4} and as default the useragent (for the 64bit version) is like this: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.1) Gecko/20141107 PaleMoon/25.0.2

**Comment by webkodierer** [comment]
Ok, lets try. 
The firefox version now is packed with jpm. 
Palemoon needs addon-sdk / cfx? Which version? What exactly needs to be done? 
If possible we might deliver with the next release.

**Comment by beerisgood** [comment]
Pale Moon addons need the Pale Moon SDK: https://github.com/MoonchildProductions/Pale-Moon/tree/master/addon-sdk
